name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows
            os: windows-latest

          - name: macOS
            os: macos-latest

          - name: Android32
            os: ubuntu-latest
            target: Android32

          - name: Android64
            os: ubuntu-latest
            target: Android64

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install NASM
        uses: ilammy/setup-nasm@v1
        if: matrix.config.name == 'Windows'

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          export-pdb: true
          combine: true
          target: ${{ matrix.config.target }}

  package:
    name: Package builds
    runs-on: ubuntu-latest
    needs: ['build']

    steps:
      - uses: geode-sdk/build-geode-mod/combine@main
        id: build

      - uses: actions/upload-artifact@v4
        with:
          name: Build Output
          path: ${{ steps.build.outputs.build-output }}

      - name: Check if has nightly webhook
        id: check
        run: echo "::set-output name=has-nightly-webhook::${{ secrets.NIGHTLY_WEBHOOK != '' }}"

      - name: Get commit messages
        id: commit
        run: |
          echo "::set-output name=commit-message::$(git log -1 --pretty=format:"%s")"
          echo "::set-output name=commit-message-full::$(git log -1 --pretty=format:"%B")"

      - name: Upload release to Discord
        uses: prevter/discord-webhook@main
        if: ${{ steps.check.outputs.has-nightly-webhook == 'true' }}
        with:
          webhook-url: ${{ secrets.NIGHTLY_WEBHOOK }}
          files: ${{ steps.build.outputs.build-output }}/*.geode
          embed-title: ${{ steps.commit.outputs.commit-message }}
          embed-description: ${{ steps.commit.outputs.commit-message-full }}
          embed-color: ${{ github.sha }}
          embed-author-name: ${{ github.actor }}
          embed-url: ${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}
          embed-author-icon: ${{ github.event.sender.avatar_url }}
          embed-timestamp: 'now'
